// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupSYiRp59zscKFA7ir8v7Curq1Fi6lF4',
    appId: '1:773511856450:web:a7335e24005c4d1cb648db',
    messagingSenderId: '773511856450',
    projectId: 'ryde-rw',
    authDomain: 'ryde-rw.firebaseapp.com',
    storageBucket: 'ryde-rw.firebasestorage.app',
    measurementId: 'G-4CSP4S1VHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjAnxqtazz0001q_bCY_dXVn6Qh4dQAA',
    appId: '1:773511856450:android:b7fe0078febc8c36b648db',
    messagingSenderId: '773511856450',
    projectId: 'ryde-rw',
    storageBucket: 'ryde-rw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzV6xmnlOwIo38fOCVQqYamRAEOTumgpM',
    appId: '1:773511856450:ios:20f7f23bd3c1bd7db648db',
    messagingSenderId: '773511856450',
    projectId: 'ryde-rw',
    storageBucket: 'ryde-rw.firebasestorage.app',
    iosBundleId: 'com.example.rydeRw',
  );
}

